### ISSUE TITLE
Planets all appear suddenly when flying away from a selected planet

### ISSUE THREAD

**Issue by aberkie** [nclud/starwars-map#10]
Not sure if this is a performance issue or not, but there is a moment when no planets appear.

![image](https://cloud.githubusercontent.com/assets/1800663/9549932/836b3536-4d76-11e5-98c1-c66cc6599f4b.png)

**Comment by aberkie** [comment]
Still happening on chrome

**Comment by kyleconrad** [comment]
Right, there's no way to change the behavior on this. I can't "fade in" or "fade out" planets, only make them visible or not. Having them appear suddenly at the end of an animation, while a tiny bit jarring, ensures the best performance across all devices (found this out through lots of testing).
