### ISSUE TITLE
Info tab appears at bottom of page

### ISSUE THREAD

**Issue by ksung** [nclud/starwars-map#3]
This is on Chrome Version 44.0.2403.157 (64-bit)

![screen shot 2015-08-28 at 11 03 16 am](https://cloud.githubusercontent.com/assets/913123/9549584/c5d24d44-4d74-11e5-9d4a-e4e64a4cbc96.png)

**Comment by kyleconrad** [comment]
Screen size?

**Comment by ksung** [comment]
1541 wide, 1200+ tall
