### ISSUE TITLE
Plannets buried in galaxy

### ISSUE THREAD

**Issue by aberkie** [nclud/starwars-map#9]
Is this look intentional? It makes the depth perspective feel a little weird.

![screen shot 2015-08-28 at 11 13 26 am](https://cloud.githubusercontent.com/assets/1800663/9549826/f2c5692a-4d75-11e5-9c15-bc9ea389a21f.png)

**Comment by kyleconrad** [comment]
It is - played with different variation on galaxy height and placement, but it looked even weirder and out of place with the galaxy not "centered" with the planets.
